### Get all reviews
GET http://localhost:3030/api/v1/products/68bfcf396a8e789bd4154517/reviews

### Add a review
POST http://localhost:3030/api/v1/products/68bfcf396a8e789bd4154517/reviews
Content-Type: application/json

{
    "rating": 2,
    "comment": "Awesome",
    "isPinned": false
}

### Update a review -> endpoint /products/:productId/reviews/:reviewId
PATCH http://localhost:3030/api/v1/products/68bfcf396a8e789bd4154517/reviews/68c3ceac5c573aebd597611d
Content-Type: application/json

{
    "rating": 4,
    "comment": "Awesome",
    "isPinned": true
}

### Delete a review
DELETE http://localhost:3030/api/v1/products/68bfcf396a8e789bd4154517/reviews/68c3ceac5c573aebd597611d

### Toggle pinned a review
PATCH http://localhost:3030/api/v1/products/68bfcf396a8e789bd4154517/reviews/68c29f05c8a77d726d423f0f/pin